[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "polaris-is"
version = "0.1.0"
description = ""
dependencies = [
    "grpcio",
    "protobuf"
]

[project.scripts]
polar-is = "polar_is.cli:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]